"""change chunk_metadata to JSONB

Revision ID: 834dde97e0f2
Revises: b2f8532c155b
Create Date: 2026-04-17 13:47:29.504016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '834dde97e0f2'
down_revision: Union[str, None] = 'b2f8532c155b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'chunks',
        'chunk_metadata',
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using='chunk_metadata::jsonb'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chunks',
        'chunk_metadata',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using='chunk_metadata::text'
    )
