from enum import Enum
class ResponseStatus(Enum):
    FILE_VALIDATED_SUCCESS = "file_validate_successfully"
    FILE_TYPE_NOT_SUPPORTED = "file_type_not_supported"
    FILE_SIZE_EXCEEDED = "file_size_exceeded"
    FILE_UPLOAD_SUCCESS = "success"
    FILE_UPLOAD_FAILED = "file_upload_failed"
    FILE_NOT_FOUND="file_not_found"
    FILE_PROCESS_SUCCESS="success"
    FILE_PROCESS_FAILED="file_process_failed"
    FILE_LIST_SUCCESS="get_file_list_success"
    FILE_LIST_FAILED="get_file_list_failed"
    NO_FILES_ERROR="no file error"
    FILE_ID_ERROR="File ID not found"
    PROJECT_NOT_FOUND="project not found"
    INSERT_INTO_VECTORDB_ERROR= "insert _into_vectordb_error"
    INSERT_INTO_VECTORDB_SUCCESS= "success"
    GET_VECTORDB_COLLECTION_INFO_SUCCESS= "get_vectordb_collection_info_success"
    VECTOR_SEARCH_SUCCESS= "vector_search_success"
    VECTOR_SEARCH_FAILED= "vector_search_failed"
    RAG_ANSWER_FAILED= "rag_answer_failed"
    RAG_ANSWER_SUCCESS= "rag_answer_success"
    TRANSLATION_SUCCESS= "translation_success"
    TRANSLATION_FAILED= "translation_failed"
    TRANSLATION_JOB_CREATED= "translation_job_created_success"
    TRANSLATION_STATUS_SUCCESS= "translation_status_success"
    TRANSLATION_STATUS_FAILED= "translation_status_failed"
    PROJECT_DELETE_SUCCESS="project_delete_success"
    PROJECT_DELETE_FAILED="project_delete_failed"
    PROJECT_ID_ERROR="project_id_error"
    

